/**
 * Amberdata Web3API for Gas Predictions
 * This is an OpenAPI document for Amberdata Gas Predictions https://docs.amberdata.io/reference#get-gas-predictions
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ericglau@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.demo.api;

import com.example.demo.models.Payload;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;
import org.apache.cxf.jaxrs.ext.multipart.*;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

/**
 * Amberdata Web3API for Gas Predictions
 *
 * <p>This is an OpenAPI document for Amberdata Gas Predictions https://docs.amberdata.io/reference#get-gas-predictions
 *
 */

@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/")
public interface Web3Api  {

    /**
     * gas predictions
     *
     * Retrieves the latest gas predictions for the transactions. 
     *
     */
    @GET
    @Path("/api/v2/transactions/gas/predictions")
    @Produces({ "application/json" })
    public Payload gasPredictions(@HeaderParam("x-api-key")  String xApiKey, @HeaderParam("x-amberdata-blockchain-id")  String xAmberdataBlockchainId) throws ApiException, ProcessingException;
}

